{% set version = "1.1-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-icsnp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ICSNP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ICSNP/ICSNP_{{ version }}.tar.gz
  sha256: 7a4b11d9bd74099fd31f802e438605ab5d181a47754018e5eb6deeebec6ad6c3

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ics
    - r-mvtnorm
  run:
    - r-base
    - r-ics
    - r-mvtnorm

test:
  commands:
    - $R -e "library('ICSNP')"           # [not win]
    - "\"%R%\" -e \"library('ICSNP')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ICSNP
  license: GPL (>= 2)
  summary: Tools for multivariate nonparametrics, as location tests based on marginal ranks, spatial median and spatial signs computation, Hotelling's T-test, estimates of shape are implemented.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: ICSNP
# Type: Package
# Title: Tools for Multivariate Nonparametrics
# Version: 1.1-1
# Date: 2018-03-10
# Author: Klaus Nordhausen, Seija Sirkia, Hannu Oja, David E. Tyler
# Maintainer: Klaus Nordhausen <klaus.nordhausen@tuwien.ac.at>
# Depends: R (>= 2.4.0), mvtnorm, ICS
# Description: Tools for multivariate nonparametrics, as location tests based on marginal ranks, spatial median and spatial signs computation, Hotelling's T-test, estimates of shape are implemented.
# License: GPL (>= 2)
# Encoding: latin1
# NeedsCompilation: yes
# Packaged: 2018-03-10 22:25:09 UTC; klanor
# Repository: CRAN
# Date/Publication: 2018-03-10 23:03:38 UTC
