{% set version = '1.1-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-icsnp
  version: {{ version|replace("-", "_") }}

source:
  fn: ICSNP_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ICSNP_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ICSNP/ICSNP_{{ version }}.tar.gz

  sha256: fe04e11cd1ede2896d952976943c2f164be4260abde8845285663c1aa944f6bc

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-ics
    - r-mvtnorm

  run:
    - r-base
    - r-ics
    - r-mvtnorm

test:
  commands:
    - $R -e "library('ICSNP')"  # [not win]
    - "\"%R%\" -e \"library('ICSNP')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ICSNP
  license: GPL (>= 2)
  summary: Tools for multivariate nonparametrics, as location tests based on marginal ranks,
    spatial median and spatial signs computation, Hotelling's T-test, estimates of shape
    are implemented.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
