travis:
  secure:
    BINSTAR_TOKEN: jHvl1e8p2peipR4Q47iJ0Dwm6Lq41pDb7Y5EdMX2CkJS+UTcR0gZj07Ena8uGUANWV5dBrCPsm+f9jnHSAEgub4aiy6pMFRKX+C9R1LlVGafiaKXjNxmTkd8DuqYwNUPgeQxhbx0OlunaB7Mwl3KlWfS0UEQXwQ5A3Yr7Mu44tfV3g8R7O8Kr5jFrTyNLUkAghHMxd614ek1uptbXkBt1xVe1ondwqsq1cCHdxPv0XHQyoa33zjD4oXNnsbJ0EBKNNP0OhciDQDd2t29P8gGROxIps53WrOj9TuJTGtQe98zDKbnYIYUIT0MsNx9BE68sEhsVrhTpEtk8wIeyWh/3ERurpwEWFr/H9R6Ka3Rnf+5Yu93qxZWISb27Rjiwrr4ZRfkJH0kSqZTRfxuJU2GDrlkz03cDwrawG8ovPrxP8VWjGBqtM4sizJuHKPhmCORrP/Rbkz2QXjXUhZ5L9TLhD+xZdt45jEyWl2+op/+ZvYRNX3suAwUT+Q+EJGvrxnfbgvbPqtSNPt2CzERuZqMUSok9HW6pKEZ4l1FgZ3VGoARXycn0Al6wS1r/3MY5yaeVQcR6F0YrT4YVUZMzazB45dFvDSj0gumq3V8JHLmY55t0n6p2pB2M+we1/9ltJQn/oeCVBJBcyRM/9eZEdIRBMn78687XHH/X/Ue0hSm3Hs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
