appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Rzkiaai/c7IJBe0VqSB9LGyarf3ZiOTwC+9dGrGwsbx5sdgo3lNrTrRj5RDM6gClNj4bz2SLY1G3CLPsULfsVjG74XNlDR8xJppWaESdAAPFh5YgtOdQlsXBRHkP/ER7LuTHKVs+/sZzaasRUxXRJ7cjB9y1XiRKg61EzzhPZZNVD/430AelsDGX0oDxMw4nGhQeBlYX+jd0r+q+U5zsBdi38VeGelkx3z/8Ihofy9W4beFmRsUm3bd0TvkkIvyVN7YqVqU0ZaooLpxhEHJfr2oJOhpudwN85EnXFb1CYTD/Iq5HBFNqHWY/WAdKz+gk0M8mg/FIKF7GNafG4R5jXsq+Oa2lPLK8/vJ9Qnbe3OPHiMy9lcDvII/ALFFBeFsTuCYv8ZJo3qR6WZLr4hdhES9wuNZ02OPXJpw6eLDpXcBAqyID7+K8+O7ESTyOdD7sEnPolXnZua8Ad4NK52bcumm5Lc99rRo29YEJTzggzFKhVQTIZbspu6NYcFK2x4m8qwXnoP03Y21oRJ1LQJypmsmHGEllaNkQs98ieQNw0zB7JPE2flIDjIXuZJzyQ4DZ/d/STZ09zDsYafZ9sE5CkpKhitWsr6Ewd/3BlAypugCP/K3FonXDeE97bx9BfFDZ96ScjUV1Xca/rB8IWNPG90vpptg3E5ZZzgG5fZu24Jw=}
