travis:
  secure:
    BINSTAR_TOKEN: UFCE5SlRzsXuDU6n2Ai7Xmo8RJLaW83i98rRGJqLPSQvJpeI2dRnhWq1NVDb99tPtzXVU7Vz7TZfT720HbY/9dZVt3HXGOIlH2TI9NaYjI/Lt1j8C4zxVXOeOLLUXUVPGy0ip3xDPli8DH4sDhTEMY+jx5Z0PxgoY/7NtEpAcNKwQqnWi055+ohu5kKXB4yb4CAXlwhACCBg4g1c2zSTo+vacl2CTwwYghBOHomtvGSa7kW4YTnEGMKd9dusgRnxoL+f6pOHhBInxhuvlFuNiobaV+KXNtzHI4Fq4pB37EJ5YjjIWJHrcqhYQCh+hvvKMnjb3bsfi5hImMaw1XgotMF+f4dRvWn7VoAqlc9GyuiHmeV9Qn4V3Uw0lS9iwL/xXChyd3k0pUbVm3oOgQDm5vzPIk8GXexoKJYEibD4PzbzNLWYRs57A1+htW/f0YKAG1MKxShpn4B3V4beM8ljWiPppJXRGcVT5xg/8ZNvmCDuVXhSC/Ss5ILemw7wAbqIe81Y+dc/P/n8dq0YpswXA5rNQsfjLr2oLRyQNhwuEtH/hm0ZMiKMzHtjYfPsmdxUpfQ6qUM6N0eVrP3q13xh0hLF/HS0RBN/v2KATBqhG8kYUvxRvLMBDMTMEEkzDos8Ix98hV4Hl+IlzwQQRqsm3jmIPpvlsZeb4EZzqwGFFZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
